
name: Variables and Secrets in Github Actions

 
on:
 
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  author = branch["main"]



jobs:
 
  build:
    
    runs-on: ubuntu-latest
    env:
        baseapi: https://baseurl.api/

   
    steps:
     
      - uses: actions/checkout@v4

      - name: All Type of Variables and Secrets
        run: |
          echo "Workflow Variables | $author has created the api $baseapi which will expire in $expire"
          echo "Configuration Variable | Version of App is ${{ vars.VERSION }}"
          echo "Secret| Secret Key is ${{ vars.secrets_KEY }}"
          ${{secrets.KEY_VISIBLE}}
          echo "Content Variables | Repo Name is ${{ github.respository }}"
        env:
           expire: 10days

